version: "2"

run:
  timeout: 5m
  tests: true

linters:
  default: fast
  enable:
    - errcheck
    - revive
  disable:
    - depguard
    - wsl

issues:
  max-same-issues: 0
  max-issues-per-linter: 0
